spring:
  datasource:
    url: jdbc:mysql:///vueblog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8081
